# Build Docker image for this app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- script: |
    npm install
    npm test
    docker build -f Dockerfile -t $(dockerId)/$(imageName) .
    echo $(MY_PASSWORD) | docker login -u $(dockerId) --password-stdin
    docker push $(dockerId)/$(imageName)

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact: $(Build.DefinitionName)-docker"
  inputs:
    PathtoPublish: ./
    ArtifactName: docker
